"""
Chapters 1-3: Introduction, Literature Review, Problem Definition.
"""
from report_helpers import *


def write_chapter1(doc):
    add_chapter(doc, 1, "Introduction")

    add_section(doc, "1.1", "Background")
    add_para(doc, "Road traffic accidents remain one of the leading causes of death and disability worldwide. According to the World Health Organization (WHO), approximately 1.35 million people die annually in road traffic crashes, with an additional 20–50 million sustaining non-fatal injuries [1]. Among the various contributing factors, driver drowsiness has been identified as a critical and preventable cause, accounting for an estimated 15–20% of all fatal road accidents across multiple national databases [2]. The European Transport Safety Council and the National Highway Traffic Safety Administration (NHTSA) in the United States have both reported that fatigue-related crashes disproportionately occur during monotonous highway driving and during circadian low periods, particularly between 2:00 AM and 6:00 AM [3].")
    add_para(doc, "The neurophysiological basis of drowsiness is well established in the clinical literature. As a driver transitions from an alert state toward sleep, characteristic changes occur in electroencephalographic (EEG) signals. Specifically, theta-band activity (4–8 Hz) increases progressively, reflecting the slowing of cortical processing associated with reduced vigilance [4]. Concurrently, alpha-band power (8–13 Hz) undergoes complex modulation — initially increasing during relaxed wakefulness and subsequently redistributing as the subject approaches sleep onset [5]. Beta-band activity (13–30 Hz), which is associated with active cognitive engagement and alertness, diminishes as drowsiness deepens. The ratio of theta power to alpha power (θ/α) has therefore been established as a robust composite biomarker for drowsiness estimation, as it simultaneously captures both the increase in slow-wave activity and the reduction in alert-state oscillations [6].")
    add_para(doc, "Existing driver monitoring systems (DMS) can be broadly categorised into three approaches: camera-based behavioural monitoring, physiological signal monitoring, and vehicle dynamics analysis. Camera-based systems, such as those deployed by Seeing Machines and Smart Eye across more than 370 vehicle models [7], detect drowsiness by tracking eyelid closure (PERCLOS), yaw frequency, and head pose. While commercially dominant, these systems are inherently reactive — they detect drowsiness only after its behavioural manifestations have become visible, leaving insufficient time for preventive action. Furthermore, camera-based systems are susceptible to limitations including poor lighting conditions, sunglasses, and privacy concerns associated with continuous facial imaging.")
    add_para(doc, "Physiological approaches, particularly EEG-based monitoring, offer a more direct measure of the neural substrates of drowsiness. However, traditional EEG systems require multi-channel electrode caps with conductive gel, making them impractical for consumer automotive applications. Recent advances in dry electrode technology and minimal-channel configurations have begun to address these barriers, but the field remains dominated by reactive classification paradigms that diagnose current drowsiness state rather than predicting future onset [8].")

    add_section(doc, "1.2", "Problem Statement")
    add_para(doc, "Current driver drowsiness detection systems suffer from four critical limitations that collectively prevent effective proactive intervention:")
    add_para(doc, "First, existing systems are reactive rather than proactive. They detect drowsiness only after physiological or behavioural symptoms have already manifested, providing the driver with little to no actionable lead time. A system that merely confirms that a driver is currently drowsy adds limited safety value compared to one that warns 5–10 minutes before drowsiness becomes dangerous.")
    add_para(doc, "Second, most EEG-based research systems require multi-channel electrode configurations (8–32 channels or more), gel-based electrodes, and cumbersome headgear that no consumer driver would tolerate during routine driving. The gap between laboratory-grade EEG systems and practical automotive deployment remains substantial.")
    add_para(doc, "Third, no commercially available system integrates EEG sensors into the vehicle headrest in a passive, wearable-free configuration that operates transparently without requiring any action from the driver beyond sitting normally.")
    add_para(doc, "Fourth, the cost of existing physiological monitoring solutions ranges from $1,000 to over $10,000 per unit, placing them beyond the reach of mass-market automotive deployment. A viable consumer solution must achieve comparable accuracy at a cost of $100–500.")

    add_section(doc, "1.3", "Proposed Solution")
    add_para(doc, "This project presents a proactive driver monitoring system that addresses all four limitations identified above. The system employs a headrest-embedded sensor configuration using only two dry silicone-textile EEG electrodes positioned at the O1 and O2 occipital sites according to the International 10-20 system. These electrodes make passive contact with the driver's scalp through hair, requiring no gel application or conscious action from the driver.")
    add_para(doc, "The signal processing pipeline comprises a 4th-order Butterworth bandpass filter (0.5–40 Hz) for preprocessing, followed by Welch's power spectral density estimation within 60-second sliding windows to extract theta (4–8 Hz) and alpha (8–13 Hz) band power features. A Random Forest classifier with 200 decision trees was trained and validated on the DROZY clinical dataset to perform binary classification between alert and drowsy states.")
    add_para(doc, "The core innovation of this system is a temporal trend extrapolation algorithm that maintains a rolling 5-minute history buffer of the theta/alpha ratio and applies linear regression to estimate the slope of the drowsiness trend. By extrapolating this trend forward, the system calculates the predicted time until the ratio crosses a personalised danger threshold (set at 1.5× the driver's awake baseline), thereby providing 5–10 minutes of advance warning. A graduated three-tier alert system (Yellow Warning at 10 minutes, Red Alert at 5 minutes, Critical at threshold breach) ensures appropriate and escalating driver notification.")

    add_section(doc, "1.4", "Objectives")
    add_para(doc, "The specific objectives of this project were as follows:")
    add_para(doc, "1. To design a minimal 2-channel occipital EEG acquisition system concept embedded in a standard vehicle headrest using dry silicone-textile electrodes at the O1 and O2 positions.")
    add_para(doc, "2. To develop a real-time signal processing pipeline incorporating a 4th-order Butterworth bandpass filter and Welch's PSD method to extract theta and alpha band power as drowsiness biomarkers.")
    add_para(doc, "3. To train and validate a Random Forest classifier achieving ≥85% accuracy on the DROZY clinical dataset, with supplementary cross-dataset exploration on SEED-VIG.")
    add_para(doc, "4. To implement a linear regression-based proactive extrapolation algorithm capable of predicting drowsiness onset 5–10 minutes in advance and triggering a graduated 3-tier alert system.")

    add_section(doc, "1.5", "Scope of the Project")
    add_para(doc, "This project encompassed the development and validation of the complete algorithmic pipeline from raw EEG signal acquisition through to drowsiness prediction and alert generation. The scope included: signal preprocessing and filtering, frequency-domain feature extraction, machine learning classification, temporal trend analysis, prediction algorithm design, and alert system specification. Validation was performed on the DROZY clinical dataset (10 subjects, ~30 hours of EEG) with supplementary exploration on the SEED-VIG dataset (23 subjects).")
    add_para(doc, "The following aspects were outside the scope of this project: fabrication of a physical headrest prototype, clinical trials with human subjects using the headrest hardware, real-time embedded system implementation on a microcontroller, and regulatory certification. The hardware design was presented as a conceptual specification suitable for future prototyping.")

    add_section(doc, "1.6", "Organisation of the Report")
    add_para(doc, "This report is organised into six chapters. Chapter 1 provides the introduction, background, problem statement, and objectives. Chapter 2 presents a comprehensive review of related literature covering EEG-based drowsiness detection, minimal-channel configurations, machine learning classifiers, and existing driver monitoring systems. Chapter 3 formally defines the problem and objectives with alignment to the United Nations Sustainable Development Goals. Chapter 4 details the complete methodology including dataset description, signal processing pipeline, feature extraction, machine learning classification, the prediction algorithm, and the alert system design. Chapter 5 presents and discusses the results, including classification performance, prediction validation, cross-dataset exploration, and comparison with existing systems. Chapter 6 concludes the report with a summary of achievements, technical challenges encountered, scalability considerations, and recommendations for future work.")


def write_chapter2(doc):
    add_chapter(doc, 2, "Review of Literature")

    add_section(doc, "2.1", "EEG-Based Drowsiness Detection")
    add_para(doc, "Electroencephalography has been extensively investigated as a modality for drowsiness detection owing to its direct measurement of cortical neural activity. Stancin et al. [4] presented a comprehensive review of EEG signal features used in driver drowsiness detection systems, surveying over 100 studies published between 2010 and 2021. The review identified theta-band power, alpha-band power, and their various ratios as the most consistently effective features across studies, with classification accuracies ranging from 75% to 98% depending on the number of channels, feature set, and classifier employed. The authors noted that the field was converging toward frequency-domain features computed via power spectral density methods, particularly Welch's periodogram, as the preferred feature extraction approach.")
    add_para(doc, "Jap et al. [6] conducted one of the most highly cited studies in this domain (948 citations), systematically evaluating multiple EEG spectral ratio algorithms including (θ+α)/β, α/β, and θ/β for drowsiness assessment. Their work established that spectral power ratios were superior to absolute band powers for drowsiness classification, as ratios inherently normalise inter-subject variability. This finding directly informed the present project's use of the theta/alpha ratio as the primary drowsiness biomarker.")
    add_para(doc, "Sahayadhas et al. [3] provided an early but influential review of sensor-based drowsiness detection approaches, comparing EEG-based methods with other physiological signals including electrooculography (EOG), electromyography (EMG), and electrocardiography (ECG). The review concluded that EEG offered the highest sensitivity to drowsiness onset but noted the practical barrier of multi-channel, gel-based electrode systems for real-world deployment.")

    add_section(doc, "2.2", "Theta/Alpha Ratio as a Drowsiness Biomarker")
    add_para(doc, "The neurophysiological rationale for the theta/alpha ratio as a drowsiness biomarker rests on two well-established phenomena. First, theta-band power (4–8 Hz) increases progressively as cortical arousal decreases, reflecting the transition from active wakefulness toward the hypnagogic state preceding sleep onset [6]. Second, alpha-band power (8–13 Hz), which is dominant during relaxed wakefulness, undergoes redistribution during the drowsiness process. The ratio θ/α therefore amplifies both effects simultaneously — a rising numerator and a changing denominator — producing a biomarker with greater sensitivity than either band power alone.")
    add_para(doc, "Gangadharan and Vinod [9] investigated drowsiness detection using portable wireless EEG devices and reported that temporal and occipital electrode sites provided more significant drowsiness-related features compared to frontal sites. This finding is particularly relevant to the present project, as it validates the choice of O1 and O2 occipital electrodes for a headrest-based system where the occipital region naturally contacts the headrest surface.")

    add_section(doc, "2.3", "Minimal-Channel EEG for Fatigue Detection")
    add_para(doc, "The feasibility of drowsiness detection with reduced electrode configurations has been a growing area of research. LaRocco et al. [8] reviewed low-cost EEG headsets for drowsiness detection and established an 80% accuracy threshold as the minimum requirement for a viable drowsiness detection system. Their analysis of commercial devices including the NeuroSky MindWave (single-channel), Emotiv EPOC (14-channel), and OpenBCI (8–16 channel) revealed a clear trade-off between sensor count and classification performance, with diminishing returns beyond 4–8 channels for binary drowsiness classification.")
    add_para(doc, "Balam [10] presented a systematic review of single-channel EEG-based drowsiness detection approaches in the IEEE Transactions on Intelligent Transportation Systems. The review found that single-channel systems typically achieved 70–82% accuracy, which falls below the 85% threshold required for safety-critical applications. However, the review noted that 2-channel configurations could achieve significantly higher accuracy by leveraging bilateral signal redundancy. The present project's 2-channel O1/O2 configuration represents this optimal balance — achieving 89.54% accuracy while maintaining the simplicity required for headrest integration.")

    add_section(doc, "2.4", "Machine Learning Classifiers for EEG-Based Drowsiness Detection")
    add_para(doc, "A variety of machine learning classifiers have been applied to EEG-based drowsiness detection. Jeong et al. [11] proposed a deep spatio-temporal convolutional bidirectional LSTM network for multi-level drowsiness classification, achieving high accuracy but requiring substantial computational resources unsuitable for embedded automotive deployment. Cheng et al. [12] explored temporal EEG imaging for drowsy driving prediction using linear combinations of temporal image sequences, representing one of the few studies to explicitly address prediction rather than current-state detection.")
    add_para(doc, "Random Forest classifiers have been widely adopted for EEG classification tasks due to their robustness to overfitting, interpretable feature importance rankings, and suitability for real-time deployment with low computational overhead. Chowdhury et al. [5] reviewed sensor applications for driver monitoring and confirmed that ensemble methods, particularly Random Forests, consistently performed well on frequency-domain EEG features, achieving accuracies comparable to deep learning approaches but with significantly lower inference times (<50 ms per classification).")

    add_section(doc, "2.5", "Existing Driver Monitoring Systems")
    add_para(doc, "The commercial driver monitoring landscape is currently dominated by camera-based systems. Seeing Machines and Smart Eye together serve more than 390 vehicle models across 24 OEMs, using infrared cameras to track eye closure percentage (PERCLOS), yaw frequency, and head pose [7]. These systems are reactive, detecting current drowsiness state based on observable behavioural symptoms. While camera systems have achieved regulatory acceptance under EU Regulation 2019/2144 (which mandates driver drowsiness warning systems for new vehicles from 2024), they offer no advance prediction capability.")
    add_para(doc, "In the EEG domain, the Neurovigil patent (US12446811B2, 2025) [13] represents the most directly competing technology, claiming a multi-modal biosignal integration system with headrest-embedded electrodes for real-time alertness prediction. However, the Neurovigil system employs EEG, EOG, and EMG sensors simultaneously, relies on generic \"real-time prediction\" (likely reactive classification), and does not claim a specific advance prediction timeline. The Toyota patent (US11091168B2, 2021) [14] describes a headrest-integrated magnetoencephalography (MEG) system for drowsiness detection, but MEG technology costs exceed $10,000 per unit and requires magnetic shielding, making it impractical for mass-market deployment.")

    add_table(doc,
        ["Feature", "Our System", "Neurovigil (2025)", "Toyota MEG (2021)", "Camera Systems"],
        [
            ["Prediction", "5–10 min advance", "Generic 'prediction'", "Current state only", "Current state only"],
            ["Sensors", "O1 + O2 (headrest)", "EEG+EOG+EMG", "MEG (lab-grade)", "Camera"],
            ["Form Factor", "Headrest", "Headrest/Wearable", "Headrest", "Dashboard"],
            ["Cost", "$100–500", "$1,000+", "$10,000+", "$200–1,000"],
            ["Accuracy", "89.54%", "Not reported", "Not reported", "70–85%"],
            ["Privacy", "High (no images)", "High", "High", "Low (facial images)"],
        ],
        "2.1", "Comparison of the Proposed System with Existing Driver Monitoring Technologies")

    add_section(doc, "2.6", "Proactive and Predictive Approaches")
    add_para(doc, "The distinction between reactive detection and proactive prediction is critical. Reactive systems answer the question \"Is the driver drowsy now?\" — a diagnosis of current state. Proactive systems answer \"When will the driver become dangerously drowsy?\" — a forecast of future state. Despite the clear safety advantage of proactive prediction, the literature reveals a significant gap: no existing system, whether patented or academically published, explicitly demonstrates advance drowsiness prediction with a quantified timeline of 5–10 minutes.")
    add_para(doc, "Nguyen et al. [15] combined EEG and near-infrared spectroscopy (NIRS) for drowsiness prediction using time-series analysis of oxy-haemoglobin concentration. While this represents a prediction approach, the system required multi-modal sensing (EEG + optical) and did not quantify a specific advance prediction horizon. Lin et al. [16] proposed a generalised drowsiness prediction framework but used the term \"prediction\" loosely, likely referring to current-state classification from temporal features rather than genuine future-state forecasting.")
    add_para(doc, "The gap identified through this literature review is clear: no existing system combines (1) proactive temporal extrapolation with a quantified 5–10 minute prediction window, (2) a headrest-embedded form factor, (3) an occipital-only minimal 2-channel EEG configuration, and (4) consumer-viable cost ($100–500). The present project addresses this gap.")

    add_section(doc, "2.7", "Preliminary Cost and Feasibility Analysis")
    add_para(doc, "The proposed system achieves its cost target through three design decisions. First, the use of only two EEG channels eliminates the expensive multi-channel amplifier systems required by research-grade devices ($5,000–$50,000). Second, dry silicone-textile electrodes eliminate the need for conductive gel and specialised preparation, reducing consumable costs to near zero. Third, the signal processing algorithm (Butterworth filter + Welch PSD + linear regression) is computationally lightweight and can execute on an ARM Cortex-M4 microcontroller costing less than $10 in volume production.")
    add_para(doc, "The estimated bill of materials for a production headrest module is: dry electrodes ($5–15), 2-channel EEG analog front-end IC ($15–30), ARM Cortex-M4 microcontroller ($8–12), wireless module ($5–10), PCB and passives ($10–20), headrest integration ($30–50). Total estimated hardware cost: $73–137, with retail pricing in the $100–500 range depending on OEM integration and volume.")
    add_para(doc, "The validation dataset (DROZY) is publicly available at no cost, and all processing was performed using open-source software libraries (MNE-Python, scikit-learn, SciPy), further reducing development barriers.")

    add_section(doc, "2.8", "Societal and Industry Significance")
    add_para(doc, "The proposed system aligns with two United Nations Sustainable Development Goals. SDG 3 (Good Health and Well-Being) is directly addressed through the reduction of drowsy-driving fatalities, which currently account for an estimated 270,000 deaths annually worldwide. SDG 9 (Industry, Innovation, and Infrastructure) is addressed through the development of a novel, scalable technology suitable for integration into existing vehicle manufacturing processes.")
    add_para(doc, "From an industry perspective, EU Regulation 2019/2144 mandates driver drowsiness and attention warning systems for all new vehicles sold in the European Union from July 2024. While camera-based systems currently dominate compliance solutions, an EEG-based proactive prediction system could serve as a premium complementary technology offering superior advance warning capabilities. The passive headrest form factor ensures that driver adoption requires no behavioral change, addressing one of the primary barriers to physiological monitoring system acceptance.")


def write_chapter3(doc):
    add_chapter(doc, 3, "Problem Definition and Objectives")

    add_section(doc, "3.1", "Problem Definition")
    add_para(doc, "Driver drowsiness is responsible for approximately 20% of fatal road accidents globally, yet existing monitoring technologies detect drowsiness only after its onset, providing the driver with insufficient time for safe intervention. The current state of the art in driver monitoring suffers from four specific gaps:")
    add_para(doc, "Gap 1 — Reactive detection paradigm: All commercially deployed driver monitoring systems (camera-based, steering-pattern-based, or lane-departure-based) detect current drowsiness symptoms rather than predicting future drowsiness onset. By the time a reactive system generates an alert, the driver may already be impaired.")
    add_para(doc, "Gap 2 — Sensor complexity and wearability: EEG-based drowsiness detection research predominantly relies on multi-channel (8–32 channel) electrode caps with conductive gel, which are impractical for daily driving use. Single-channel systems have been explored but achieve insufficient accuracy (<82%) for safety-critical applications.")
    add_para(doc, "Gap 3 — Absence of passive integration: No commercially available system integrates EEG sensors into the vehicle headrest in a transparent, wearable-free configuration that requires no action from the driver.")
    add_para(doc, "Gap 4 — Cost barrier: Existing physiological monitoring solutions cost $1,000–$10,000+ per unit, precluding mass-market automotive deployment.")
    add_para(doc, "The present project addressed all four gaps by developing a proactive drowsiness prediction system using only two occipital EEG channels (O1, O2) embedded in a vehicle headrest, achieving 89.54% classification accuracy and 5–10 minute advance prediction capability at an estimated cost of $100–500.")

    add_section(doc, "3.2", "Objectives")
    add_para(doc, "The project pursued four specific objectives:")
    add_para(doc, "Objective 1: Design a minimal 2-channel occipital EEG acquisition system embedded in a standard vehicle headrest using dry silicone-textile electrodes at the O1 and O2 positions of the International 10-20 system, achieving passive scalp contact through hair without conductive gel.")
    add_para(doc, "Objective 2: Develop a real-time signal processing pipeline incorporating a 4th-order Butterworth bandpass filter (0.5–40 Hz) and Welch's power spectral density method to extract theta (4–8 Hz) and alpha (8–13 Hz) band power as quantitative drowsiness biomarkers from 60-second sliding windows with 30-second overlap.")
    add_para(doc, "Objective 3: Train and validate a Random Forest classifier achieving ≥85% accuracy on the DROZY clinical dataset (10 subjects, ~30 hours of recordings) with cross-dataset generalisation exploration on the SEED-VIG dataset (23 subjects).")
    add_para(doc, "Objective 4: Implement a linear regression-based proactive extrapolation algorithm that predicts drowsiness onset 5–10 minutes in advance by analysing temporal trends in the theta/alpha ratio, and integrate this with a graduated 3-tier alert system (Yellow Warning, Red Alert, Critical).")

    add_section(doc, "3.3", "Alignment with Sustainable Development Goals")
    add_para(doc, "SDG 3 — Good Health and Well-Being: The system directly contributes to road safety by providing advance warning of drowsiness, potentially preventing the estimated 270,000 annual fatalities caused by drowsy driving worldwide. The proactive prediction paradigm offers 5–10 minutes of additional reaction time compared to reactive systems, enabling drivers to take preventive action such as stopping for rest.")
    add_para(doc, "SDG 9 — Industry, Innovation, and Infrastructure: The headrest-embedded EEG sensor configuration represents a novel approach to vehicle safety technology. The system's low cost ($100–500) and passive operation make it suitable for integration into existing vehicle manufacturing processes, enabling scalable deployment across diverse vehicle platforms and markets.")
